name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Executar CI
        run: echo "CI executado com sucesso!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executar CD
        run: echo "CD executado com sucesso!"
